// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe6VcQrF_dH4dACE1toGA5aTBsMoeuiUU',
    appId: '1:800332426650:android:111e550086307cde0a1e23',
    messagingSenderId: '800332426650',
    projectId: 'lootahre',
    storageBucket: 'lootahre.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    // Firebase.initializeApp(
    //     options: FirebaseOptions(
    //         apiKey: "AIzaSyBZJEGlhxU7mGzuESndjmiggYaWpQm51Bk",
    //         authDomain: "",
    //         projectId: "lootahre",
    //         storageBucket: "lootahre.firebasestorage.app",
    //         messagingSenderId: "800332426650",
    //         appId: "1:800332426650:ios:2a8c139011cfdf980a1e23",
    //         measurementId: ""));

    apiKey: 'AIzaSyBZJEGlhxU7mGzuESndjmiggYaWpQm51Bk',
    appId: '1:800332426650:ios:2a8c139011cfdf980a1e23',
    messagingSenderId: '800332426650',
    projectId: 'lootahre',
    storageBucket: 'lootahre.firebasestorage.app',
    iosBundleId: 'com.nijatech.bindhaenre',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSLSn0-oMBS5LeJdcPN8sBFM3qao-_dew',
    appId: '1:927687220051:ios:871d21df27581eb267dfa6',
    messagingSenderId: '927687220051',
    projectId: 'solassess-f0860',
    authDomain: 'push-notification-df5a5.firebaseapp.com',
    storageBucket: 'solassess-f0860.appspot.com',
  );
}
